---
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
      - id: codespell
        name: codespell
        entry: codespell --ignore-words-list=hass --skip="./.*" --quiet-level=2
        language: system
        types_or: [python, markdown, yaml]
        exclude: ^tests/fixtures/|homeassistant/generated/|tests/components/.*/snapshots/
      - id: yamllint
        name: yamllint
        entry: 'yamllint -d "{extends: default, rules: {line-length: {max: 999, level: warning}}}"'
        language: system
        types: [yaml]
      - id: python-typing-update
        name: python-typing-update
        entry: python-typing-update --py311-plus --force --keep-updates
        language: system
        stages: [manual]
        types: [python]
        files: ^(custom_components|tests|script)/.+\.py$
      - id: pymarkdown
        name: pymarkdown
        entry: pymarkdown scan
        language: system
        types: [markdown]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: ^venv/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
